version: '3.8'
services:
  nodejs:
    build:
      context: ./nodejs/
      dockerfile: Dockerfile
    volumes:
      - ./app/${NEXTJS_APP_NAME}:/usr/src/app/${NEXTJS_APP_NAME} # アプリケーションの相対パスを.env指定
    command: sh -c "cd ${NEXTJS_APP_NAME} && ls -a && npm run dev" # .envにプロジェクト名を定義
    ports:
      - "3000:3000"